#!/usr/bin/env bash

fin project rm -f
fin project start
fin composer install --no-progress --prefer-dist --optimize-autoloader
cp "${PROJECT_ROOT}/.docksal/files/settings.local.php" "${PROJECT_ROOT}/${DOCROOT}/sites/default/settings.php"
chmod 644 "${PROJECT_ROOT}/${DOCROOT}/sites/default/settings.php"
fin drush site-install 'minimal' --config-dir=../config/sync --account-name='admin' --account-pass='admin' --yes
#fin drush cset system.site uuid "870499f1-1a41-4439-b2ea-fdb5c1842d38" -y
fin drush deploy
fin drush locale-check
fin drush locale-update
fin drush cache-rebuild
